// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241216184211_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Branchies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Branchies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "General Şixlinski küçəsi,264 saylı məktəbin yanı",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(2287),
                            IsDeleted = false,
                            Name = "Əhmədli filialı"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Şeyx Məhəmməd Xiyabani 51",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(2290),
                            IsDeleted = false,
                            Name = "Yasamal filialı"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Binəqədi şosesi 1. Binəqədi 4yol",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(2292),
                            IsDeleted = false,
                            Name = "Binəqədi filialı"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Yavər Əliyev 68A",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(2294),
                            IsDeleted = false,
                            Name = "Bakıxanov filialı"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Xətai-8 noyabr prospekti, günəş petrol ydm-in içi",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(2295),
                            IsDeleted = false,
                            Name = "Xətai filialı"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Sumqayıt-çerkasski 78",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(2297),
                            IsDeleted = false,
                            Name = "Sumqayıt filialı"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Gəncə şəhəri, Əli Məmmədov küçəsi (3 Nömrəli xəstəxananın yanı)",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(2299),
                            IsDeleted = false,
                            Name = "Gəncə filialı"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Xaçmaz şeheri Xacmaz Xudat yolu Qımıl restoranın yanı",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(2301),
                            IsDeleted = false,
                            Name = "Xaçmaz filialı"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Quba rayonu Heyder Eliyev prospekti Praqa restoranin yani",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(2302),
                            IsDeleted = false,
                            Name = "Quba filialı"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4711),
                            IsDeleted = false,
                            Model = "X5"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4713),
                            IsDeleted = false,
                            Model = "M3"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4715),
                            IsDeleted = false,
                            Model = "M4"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4717),
                            IsDeleted = false,
                            Model = "M2"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4718),
                            IsDeleted = false,
                            Model = "3 Series"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4720),
                            IsDeleted = false,
                            Model = "5 Series"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4721),
                            IsDeleted = false,
                            Model = "7 Series"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4723),
                            IsDeleted = false,
                            Model = "X3"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4725),
                            IsDeleted = false,
                            Model = "X4"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4726),
                            IsDeleted = false,
                            Model = "X6"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4728),
                            IsDeleted = false,
                            Model = "X7"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4730),
                            IsDeleted = false,
                            Model = "i3"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4731),
                            IsDeleted = false,
                            Model = "i4"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4734),
                            IsDeleted = false,
                            Model = "iX"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4735),
                            IsDeleted = false,
                            Model = "Z4"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4737),
                            IsDeleted = false,
                            Model = "530e"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4739),
                            IsDeleted = false,
                            Model = "750i"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4740),
                            IsDeleted = false,
                            Model = "M5"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4742),
                            IsDeleted = false,
                            Model = "M8"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4743),
                            IsDeleted = false,
                            Model = "i7"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4745),
                            IsDeleted = false,
                            Model = "2 Series"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4746),
                            IsDeleted = false,
                            Model = "1 Series"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4748),
                            IsDeleted = false,
                            Model = "M6"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4750),
                            IsDeleted = false,
                            Model = "320i"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4751),
                            IsDeleted = false,
                            Model = "420i"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4753),
                            IsDeleted = false,
                            Model = "520d"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4755),
                            IsDeleted = false,
                            Model = "730d"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4756),
                            IsDeleted = false,
                            Model = "740i"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4758),
                            IsDeleted = false,
                            Model = "X1"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4759),
                            IsDeleted = false,
                            Model = "C-Class"
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4761),
                            IsDeleted = false,
                            Model = "E-Class"
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4763),
                            IsDeleted = false,
                            Model = "S-Class"
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4764),
                            IsDeleted = false,
                            Model = "A-Class"
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4767),
                            IsDeleted = false,
                            Model = "CLA-Class"
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4768),
                            IsDeleted = false,
                            Model = "GLA-Class"
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4770),
                            IsDeleted = false,
                            Model = "GLC-Class"
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4771),
                            IsDeleted = false,
                            Model = "GLE-Class"
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4773),
                            IsDeleted = false,
                            Model = "GLS-Class"
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4775),
                            IsDeleted = false,
                            Model = "SLS AMG"
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4776),
                            IsDeleted = false,
                            Model = "AMG GT"
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4778),
                            IsDeleted = false,
                            Model = "G-Class"
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4779),
                            IsDeleted = false,
                            Model = "Maybach S-Class"
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4781),
                            IsDeleted = false,
                            Model = "EQC"
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4782),
                            IsDeleted = false,
                            Model = "EQS"
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4784),
                            IsDeleted = false,
                            Model = "Coupé"
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4785),
                            IsDeleted = false,
                            Model = "Roadster"
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4787),
                            IsDeleted = false,
                            Model = "B-Class"
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4788),
                            IsDeleted = false,
                            Model = "V-Class"
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4790),
                            IsDeleted = false,
                            Model = "GLB-Class"
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4791),
                            IsDeleted = false,
                            Model = "S-Class Coupe"
                        },
                        new
                        {
                            Id = 51,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4793),
                            IsDeleted = false,
                            Model = "SL-Class"
                        },
                        new
                        {
                            Id = 52,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4794),
                            IsDeleted = false,
                            Model = "M-Class"
                        },
                        new
                        {
                            Id = 53,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4796),
                            IsDeleted = false,
                            Model = "X-Class"
                        },
                        new
                        {
                            Id = 54,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4798),
                            IsDeleted = false,
                            Model = "A4"
                        },
                        new
                        {
                            Id = 55,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4800),
                            IsDeleted = false,
                            Model = "A6"
                        },
                        new
                        {
                            Id = 56,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4802),
                            IsDeleted = false,
                            Model = "Q7"
                        },
                        new
                        {
                            Id = 57,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4803),
                            IsDeleted = false,
                            Model = "Q5"
                        },
                        new
                        {
                            Id = 58,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4805),
                            IsDeleted = false,
                            Model = "A8"
                        },
                        new
                        {
                            Id = 59,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4806),
                            IsDeleted = false,
                            Model = "Q3"
                        },
                        new
                        {
                            Id = 60,
                            Brand = "Toyota",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4808),
                            IsDeleted = false,
                            Model = "Corolla"
                        },
                        new
                        {
                            Id = 61,
                            Brand = "Toyota",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4809),
                            IsDeleted = false,
                            Model = "Camry"
                        },
                        new
                        {
                            Id = 62,
                            Brand = "Toyota",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4811),
                            IsDeleted = false,
                            Model = "RAV4"
                        },
                        new
                        {
                            Id = 63,
                            Brand = "Toyota",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4812),
                            IsDeleted = false,
                            Model = "Land Cruiser"
                        },
                        new
                        {
                            Id = 64,
                            Brand = "Toyota",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4814),
                            IsDeleted = false,
                            Model = "Hilux"
                        },
                        new
                        {
                            Id = 65,
                            Brand = "Kia",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4815),
                            IsDeleted = false,
                            Model = "Sorento"
                        },
                        new
                        {
                            Id = 66,
                            Brand = "Kia",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4817),
                            IsDeleted = false,
                            Model = "Sportage"
                        },
                        new
                        {
                            Id = 67,
                            Brand = "Kia",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4850),
                            IsDeleted = false,
                            Model = "K5"
                        },
                        new
                        {
                            Id = 68,
                            Brand = "Kia",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4852),
                            IsDeleted = false,
                            Model = "Stinger"
                        },
                        new
                        {
                            Id = 69,
                            Brand = "Hyundai",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4854),
                            IsDeleted = false,
                            Model = "Sonata"
                        },
                        new
                        {
                            Id = 70,
                            Brand = "Hyundai",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4855),
                            IsDeleted = false,
                            Model = "Tucson"
                        },
                        new
                        {
                            Id = 71,
                            Brand = "Hyundai",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4857),
                            IsDeleted = false,
                            Model = "Elantra"
                        },
                        new
                        {
                            Id = 72,
                            Brand = "Hyundai",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4858),
                            IsDeleted = false,
                            Model = "Kona"
                        },
                        new
                        {
                            Id = 73,
                            Brand = "Hyundai",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4860),
                            IsDeleted = false,
                            Model = "Palisade"
                        },
                        new
                        {
                            Id = 74,
                            Brand = "Mitsubishi",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4862),
                            IsDeleted = false,
                            Model = "Outlander"
                        },
                        new
                        {
                            Id = 75,
                            Brand = "Mitsubishi",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4863),
                            IsDeleted = false,
                            Model = "Lancer"
                        },
                        new
                        {
                            Id = 76,
                            Brand = "Mitsubishi",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4865),
                            IsDeleted = false,
                            Model = "Eclipse"
                        },
                        new
                        {
                            Id = 77,
                            Brand = "Lada",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4867),
                            IsDeleted = false,
                            Model = "Granta"
                        },
                        new
                        {
                            Id = 78,
                            Brand = "Lada",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4868),
                            IsDeleted = false,
                            Model = "Vesta"
                        },
                        new
                        {
                            Id = 79,
                            Brand = "Lada",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4870),
                            IsDeleted = false,
                            Model = "XRay"
                        },
                        new
                        {
                            Id = 80,
                            Brand = "Volkswagen",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4871),
                            IsDeleted = false,
                            Model = "Golf"
                        },
                        new
                        {
                            Id = 81,
                            Brand = "Volkswagen",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4873),
                            IsDeleted = false,
                            Model = "Passat"
                        },
                        new
                        {
                            Id = 82,
                            Brand = "Volkswagen",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4874),
                            IsDeleted = false,
                            Model = "Tiguan"
                        },
                        new
                        {
                            Id = 83,
                            Brand = "Volkswagen",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4876),
                            IsDeleted = false,
                            Model = "Jetta"
                        },
                        new
                        {
                            Id = 84,
                            Brand = "Ford",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4877),
                            IsDeleted = false,
                            Model = "Mustang"
                        },
                        new
                        {
                            Id = 85,
                            Brand = "Ford",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4879),
                            IsDeleted = false,
                            Model = "F-150"
                        },
                        new
                        {
                            Id = 86,
                            Brand = "Land Rover",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4881),
                            IsDeleted = false,
                            Model = "Range Rover"
                        },
                        new
                        {
                            Id = 87,
                            Brand = "Land Rover",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4882),
                            IsDeleted = false,
                            Model = "Discovery"
                        },
                        new
                        {
                            Id = 88,
                            Brand = "Porsche",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4884),
                            IsDeleted = false,
                            Model = "911"
                        },
                        new
                        {
                            Id = 89,
                            Brand = "Porsche",
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(4885),
                            IsDeleted = false,
                            Model = "Cayenne"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Colors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7046),
                            IsDeleted = false,
                            Name = "Ağ"
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7052),
                            IsDeleted = false,
                            Name = "Qara"
                        },
                        new
                        {
                            Id = 3,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7053),
                            IsDeleted = false,
                            Name = "Qırmızı"
                        },
                        new
                        {
                            Id = 4,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7054),
                            IsDeleted = false,
                            Name = "Yaşıl"
                        },
                        new
                        {
                            Id = 5,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7055),
                            IsDeleted = false,
                            Name = "Mavi"
                        },
                        new
                        {
                            Id = 6,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7056),
                            IsDeleted = false,
                            Name = "Sarı"
                        },
                        new
                        {
                            Id = 7,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7057),
                            IsDeleted = false,
                            Name = "Narıncı"
                        },
                        new
                        {
                            Id = 8,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7058),
                            IsDeleted = false,
                            Name = "Bənövşəyi"
                        },
                        new
                        {
                            Id = 9,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7059),
                            IsDeleted = false,
                            Name = "Çəhrayı"
                        },
                        new
                        {
                            Id = 10,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7060),
                            IsDeleted = false,
                            Name = "Boz"
                        },
                        new
                        {
                            Id = 11,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7061),
                            IsDeleted = false,
                            Name = "Qəhvəyi"
                        },
                        new
                        {
                            Id = 12,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7062),
                            IsDeleted = false,
                            Name = "Göy"
                        },
                        new
                        {
                            Id = 13,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7063),
                            IsDeleted = false,
                            Name = "Tünd yaşıl"
                        },
                        new
                        {
                            Id = 14,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7064),
                            IsDeleted = false,
                            Name = "Açıq yaşıl"
                        },
                        new
                        {
                            Id = 15,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7065),
                            IsDeleted = false,
                            Name = "Tünd mavi"
                        },
                        new
                        {
                            Id = 16,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7066),
                            IsDeleted = false,
                            Name = "Açıq mavi"
                        },
                        new
                        {
                            Id = 17,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7067),
                            IsDeleted = false,
                            Name = "Tünd qəhvəyi"
                        },
                        new
                        {
                            Id = 18,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7067),
                            IsDeleted = false,
                            Name = "Açıq qəhvəyi"
                        },
                        new
                        {
                            Id = 19,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7068),
                            IsDeleted = false,
                            Name = "Bürünc"
                        },
                        new
                        {
                            Id = 20,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7069),
                            IsDeleted = false,
                            Name = "Gümüşü"
                        },
                        new
                        {
                            Id = 21,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 984, DateTimeKind.Local).AddTicks(7070),
                            IsDeleted = false,
                            Name = "Qızılı"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Commits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommitMessage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CustumerId")
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustumerId");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("Domain.Entities.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOtp")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 985, DateTimeKind.Local).AddTicks(5272),
                            IsDeleted = false,
                            IsOtp = false,
                            Name = "Master Admin",
                            Password = "$2a$11$gZdTV78QAwiPRpd8n11MLe8p111KlStD/xo1/1qUXUBifJnwZuj8K",
                            Phone = "+994000",
                            RefreshToken = "qOLhGm3T0r6938al5PjO2nyYbnLajCGQP/XU6CJkcZ4=",
                            RefreshTokenExpiryTime = new DateTime(2025, 2, 16, 22, 42, 10, 985, DateTimeKind.Local).AddTicks(5253),
                            RoleId = 2,
                            Surname = "Master"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CustomersCarsMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ColorsId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Motor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FuelTypeId");

                    b.ToTable("CustomersCarsMatrix");
                });

            modelBuilder.Entity("Domain.Entities.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 985, DateTimeKind.Local).AddTicks(7460),
                            IsDeleted = false,
                            Name = "Master Employee",
                            Surname = "Master"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Filters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Filters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 985, DateTimeKind.Local).AddTicks(9552),
                            IsDeleted = false,
                            Name = "Yağ"
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 985, DateTimeKind.Local).AddTicks(9554),
                            IsDeleted = false,
                            Name = "Hava"
                        },
                        new
                        {
                            Id = 3,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 985, DateTimeKind.Local).AddTicks(9556),
                            IsDeleted = false,
                            Name = "Yanacaq"
                        },
                        new
                        {
                            Id = 4,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 985, DateTimeKind.Local).AddTicks(9557),
                            IsDeleted = false,
                            Name = "Salon"
                        });
                });

            modelBuilder.Entity("Domain.Entities.FuelTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 986, DateTimeKind.Local).AddTicks(1564),
                            IsDeleted = false,
                            Name = "Benzin"
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 986, DateTimeKind.Local).AddTicks(1567),
                            IsDeleted = false,
                            Name = "Qaz"
                        },
                        new
                        {
                            Id = 3,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 986, DateTimeKind.Local).AddTicks(1568),
                            IsDeleted = false,
                            Name = "Dizel"
                        },
                        new
                        {
                            Id = 4,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 986, DateTimeKind.Local).AddTicks(1570),
                            IsDeleted = false,
                            Name = "Elektro"
                        },
                        new
                        {
                            Id = 5,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 986, DateTimeKind.Local).AddTicks(1571),
                            IsDeleted = false,
                            Name = "Hybrid"
                        },
                        new
                        {
                            Id = 6,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 986, DateTimeKind.Local).AddTicks(1573),
                            IsDeleted = false,
                            Name = "Plug-in Hybrid"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OilChangeFiltersMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FilterOwn")
                        .HasColumnType("bit");

                    b.Property<int>("FiltersId")
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OilChangesId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FiltersId");

                    b.HasIndex("OilChangesId");

                    b.ToTable("OilChangeFiltersMatrix");
                });

            modelBuilder.Entity("Domain.Entities.OilChanges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomersCarsMatrixId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KilometersTravelled")
                        .HasColumnType("int");

                    b.Property<string>("OilCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OilOwn")
                        .HasColumnType("bit");

                    b.Property<decimal>("OilVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SAEViscosityId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WinterViscosityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomersCarsMatrixId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SAEViscosityId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("WinterViscosityId");

                    b.ToTable("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.Phones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 990, DateTimeKind.Local).AddTicks(8016),
                            IsDeleted = false,
                            Phone = "+994703305788"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 2,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 990, DateTimeKind.Local).AddTicks(8019),
                            IsDeleted = false,
                            Phone = "+994702343134"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 2,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 990, DateTimeKind.Local).AddTicks(8021),
                            IsDeleted = false,
                            Phone = "+994706843434"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 4,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 990, DateTimeKind.Local).AddTicks(8026),
                            IsDeleted = false,
                            Phone = "+994777332322"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 4,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 990, DateTimeKind.Local).AddTicks(8028),
                            IsDeleted = false,
                            Phone = "+994706743434"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 3,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 990, DateTimeKind.Local).AddTicks(8030),
                            IsDeleted = false,
                            Phone = "+994707552322"
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 3,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 990, DateTimeKind.Local).AddTicks(8033),
                            IsDeleted = false,
                            Phone = "+994702153434"
                        },
                        new
                        {
                            Id = 8,
                            BranchId = 3,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 990, DateTimeKind.Local).AddTicks(8035),
                            IsDeleted = false,
                            Phone = "+994702344334"
                        },
                        new
                        {
                            Id = 9,
                            BranchId = 3,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 990, DateTimeKind.Local).AddTicks(8037),
                            IsDeleted = false,
                            Phone = "+994702344334"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 990, DateTimeKind.Local).AddTicks(9744),
                            IsDeleted = false,
                            Name = "Elf"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(1322),
                            IsDeleted = false,
                            RoleName = "Costumer"
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(1324),
                            IsDeleted = false,
                            RoleName = "Branch"
                        });
                });

            modelBuilder.Entity("Domain.Entities.SAEViscosity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grade")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SAEViscosities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grade = 0,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(2968),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Grade = 5,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(2972),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Grade = 10,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(2974),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Grade = 20,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(2976),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(4945),
                            IsDeleted = false,
                            Name = "Sürətlər qutusu yağ dəyişmə"
                        },
                        new
                        {
                            Id = 2,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(4948),
                            IsDeleted = false,
                            Name = "Mühərrik yağ dəyişmə"
                        },
                        new
                        {
                            Id = 3,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(4950),
                            IsDeleted = false,
                            Name = "Antifiriz dəyişmə"
                        },
                        new
                        {
                            Id = 4,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(4952),
                            IsDeleted = false,
                            Name = "Əyləc mayesi dəyişmə"
                        },
                        new
                        {
                            Id = 5,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(4954),
                            IsDeleted = false,
                            Name = "Arxa körpü"
                        },
                        new
                        {
                            Id = 6,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(4955),
                            IsDeleted = false,
                            Name = "Ön körpü"
                        },
                        new
                        {
                            Id = 7,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 991, DateTimeKind.Local).AddTicks(4957),
                            IsDeleted = false,
                            Name = "Diferensial (Razdatka)"
                        });
                });

            modelBuilder.Entity("Domain.Entities.WinterViscosity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grade")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBrakeFluidChanged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WinterViscosities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grade = 8,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 993, DateTimeKind.Local).AddTicks(2838),
                            IsBrakeFluidChanged = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Grade = 12,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 993, DateTimeKind.Local).AddTicks(2841),
                            IsBrakeFluidChanged = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Grade = 16,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 993, DateTimeKind.Local).AddTicks(2843),
                            IsBrakeFluidChanged = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Grade = 20,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 993, DateTimeKind.Local).AddTicks(2845),
                            IsBrakeFluidChanged = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Grade = 30,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 993, DateTimeKind.Local).AddTicks(2847),
                            IsBrakeFluidChanged = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            Grade = 40,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 993, DateTimeKind.Local).AddTicks(2849),
                            IsBrakeFluidChanged = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            Grade = 50,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 993, DateTimeKind.Local).AddTicks(2851),
                            IsBrakeFluidChanged = false,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            Grade = 60,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 16, 22, 42, 10, 993, DateTimeKind.Local).AddTicks(2852),
                            IsBrakeFluidChanged = false,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Commits", b =>
                {
                    b.HasOne("Domain.Entities.Customers", "Customers")
                        .WithMany("Commits")
                        .HasForeignKey("CustumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Domain.Entities.Customers", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.CustomersCarsMatrix", b =>
                {
                    b.HasOne("Domain.Entities.Cars", "Cars")
                        .WithMany("UsersCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Colors", "Colors")
                        .WithMany("UsersCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Customers", "Customers")
                        .WithMany("CustomersCars")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FuelTypes", "FuelType")
                        .WithMany("UsersCars")
                        .HasForeignKey("FuelTypeId");

                    b.Navigation("Cars");

                    b.Navigation("Colors");

                    b.Navigation("Customers");

                    b.Navigation("FuelType");
                });

            modelBuilder.Entity("Domain.Entities.OilChangeFiltersMatrix", b =>
                {
                    b.HasOne("Domain.Entities.Filters", "Filter")
                        .WithMany("OilChangeFilters")
                        .HasForeignKey("FiltersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OilChanges", "OilChanges")
                        .WithMany("OilChangeFilters")
                        .HasForeignKey("OilChangesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filter");

                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.OilChanges", b =>
                {
                    b.HasOne("Domain.Entities.Branchies", "Branchies")
                        .WithMany("OilChanges")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CustomersCarsMatrix", "CustomersCarsMatrix")
                        .WithMany("OilChanges")
                        .HasForeignKey("CustomersCarsMatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employees", "Employees")
                        .WithMany("OilChanges")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Products", "Products")
                        .WithMany("OilChanges")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SAEViscosity", "SAEViscosity")
                        .WithMany("OilChanges")
                        .HasForeignKey("SAEViscosityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Services", "Services")
                        .WithMany("OilChanges")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.WinterViscosity", "WinterViscosity")
                        .WithMany("OilChanges")
                        .HasForeignKey("WinterViscosityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branchies");

                    b.Navigation("CustomersCarsMatrix");

                    b.Navigation("Employees");

                    b.Navigation("Products");

                    b.Navigation("SAEViscosity");

                    b.Navigation("Services");

                    b.Navigation("WinterViscosity");
                });

            modelBuilder.Entity("Domain.Entities.Phones", b =>
                {
                    b.HasOne("Domain.Entities.Branchies", "Branchies")
                        .WithMany("Phones")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branchies");
                });

            modelBuilder.Entity("Domain.Entities.Branchies", b =>
                {
                    b.Navigation("OilChanges");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Domain.Entities.Cars", b =>
                {
                    b.Navigation("UsersCars");
                });

            modelBuilder.Entity("Domain.Entities.Colors", b =>
                {
                    b.Navigation("UsersCars");
                });

            modelBuilder.Entity("Domain.Entities.Customers", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("CustomersCars");
                });

            modelBuilder.Entity("Domain.Entities.CustomersCarsMatrix", b =>
                {
                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.Employees", b =>
                {
                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.Filters", b =>
                {
                    b.Navigation("OilChangeFilters");
                });

            modelBuilder.Entity("Domain.Entities.FuelTypes", b =>
                {
                    b.Navigation("UsersCars");
                });

            modelBuilder.Entity("Domain.Entities.OilChanges", b =>
                {
                    b.Navigation("OilChangeFilters");
                });

            modelBuilder.Entity("Domain.Entities.Products", b =>
                {
                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.SAEViscosity", b =>
                {
                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.Services", b =>
                {
                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.WinterViscosity", b =>
                {
                    b.Navigation("OilChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
