// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Branchies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Branchies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Əhmədli filialı",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(4506),
                            IsDeleted = false,
                            Name = "Əhmədli"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Yasamal filialı",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(4511),
                            IsDeleted = false,
                            Name = "Yasamal"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Sumqayıt filialı",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(4513),
                            IsDeleted = false,
                            Name = "Sumqayıt"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Bakıxanov filialı",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(4514),
                            IsDeleted = false,
                            Name = "Bakıxanov"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7187),
                            IsDeleted = false,
                            Model = "X5"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7190),
                            IsDeleted = false,
                            Model = "M3"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7192),
                            IsDeleted = false,
                            Model = "M4"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7194),
                            IsDeleted = false,
                            Model = "M2"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7196),
                            IsDeleted = false,
                            Model = "3 Series"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7198),
                            IsDeleted = false,
                            Model = "5 Series"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7199),
                            IsDeleted = false,
                            Model = "7 Series"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7201),
                            IsDeleted = false,
                            Model = "X3"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7203),
                            IsDeleted = false,
                            Model = "X4"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7205),
                            IsDeleted = false,
                            Model = "X6"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7206),
                            IsDeleted = false,
                            Model = "X7"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7208),
                            IsDeleted = false,
                            Model = "i3"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7210),
                            IsDeleted = false,
                            Model = "i4"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7212),
                            IsDeleted = false,
                            Model = "iX"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7213),
                            IsDeleted = false,
                            Model = "Z4"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7215),
                            IsDeleted = false,
                            Model = "530e"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7217),
                            IsDeleted = false,
                            Model = "750i"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7219),
                            IsDeleted = false,
                            Model = "M5"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7222),
                            IsDeleted = false,
                            Model = "M8"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7223),
                            IsDeleted = false,
                            Model = "i7"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7225),
                            IsDeleted = false,
                            Model = "2 Series"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7227),
                            IsDeleted = false,
                            Model = "1 Series"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7229),
                            IsDeleted = false,
                            Model = "M6"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7231),
                            IsDeleted = false,
                            Model = "320i"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7232),
                            IsDeleted = false,
                            Model = "420i"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7295),
                            IsDeleted = false,
                            Model = "520d"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7297),
                            IsDeleted = false,
                            Model = "730d"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7299),
                            IsDeleted = false,
                            Model = "740i"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "BMW",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7301),
                            IsDeleted = false,
                            Model = "X1"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7303),
                            IsDeleted = false,
                            Model = "C-Class"
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7305),
                            IsDeleted = false,
                            Model = "E-Class"
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7307),
                            IsDeleted = false,
                            Model = "S-Class"
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7309),
                            IsDeleted = false,
                            Model = "A-Class"
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7311),
                            IsDeleted = false,
                            Model = "CLA-Class"
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7312),
                            IsDeleted = false,
                            Model = "GLA-Class"
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7314),
                            IsDeleted = false,
                            Model = "GLC-Class"
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7316),
                            IsDeleted = false,
                            Model = "GLE-Class"
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7318),
                            IsDeleted = false,
                            Model = "GLS-Class"
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7321),
                            IsDeleted = false,
                            Model = "SLS AMG"
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7322),
                            IsDeleted = false,
                            Model = "AMG GT"
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7324),
                            IsDeleted = false,
                            Model = "G-Class"
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7326),
                            IsDeleted = false,
                            Model = "Maybach S-Class"
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7327),
                            IsDeleted = false,
                            Model = "EQC"
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7329),
                            IsDeleted = false,
                            Model = "EQS"
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7331),
                            IsDeleted = false,
                            Model = "Coupé"
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7333),
                            IsDeleted = false,
                            Model = "Roadster"
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7335),
                            IsDeleted = false,
                            Model = "B-Class"
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7336),
                            IsDeleted = false,
                            Model = "V-Class"
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7338),
                            IsDeleted = false,
                            Model = "GLB-Class"
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7340),
                            IsDeleted = false,
                            Model = "S-Class Coupe"
                        },
                        new
                        {
                            Id = 51,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7342),
                            IsDeleted = false,
                            Model = "SL-Class"
                        },
                        new
                        {
                            Id = 52,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7344),
                            IsDeleted = false,
                            Model = "M-Class"
                        },
                        new
                        {
                            Id = 53,
                            Brand = "Mercedes-Benz",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7346),
                            IsDeleted = false,
                            Model = "X-Class"
                        },
                        new
                        {
                            Id = 54,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7347),
                            IsDeleted = false,
                            Model = "A4"
                        },
                        new
                        {
                            Id = 55,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7351),
                            IsDeleted = false,
                            Model = "A6"
                        },
                        new
                        {
                            Id = 56,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7353),
                            IsDeleted = false,
                            Model = "Q7"
                        },
                        new
                        {
                            Id = 57,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7355),
                            IsDeleted = false,
                            Model = "Q5"
                        },
                        new
                        {
                            Id = 58,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7356),
                            IsDeleted = false,
                            Model = "A8"
                        },
                        new
                        {
                            Id = 59,
                            Brand = "Audi",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7358),
                            IsDeleted = false,
                            Model = "Q3"
                        },
                        new
                        {
                            Id = 60,
                            Brand = "Toyota",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7361),
                            IsDeleted = false,
                            Model = "Corolla"
                        },
                        new
                        {
                            Id = 61,
                            Brand = "Toyota",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7362),
                            IsDeleted = false,
                            Model = "Camry"
                        },
                        new
                        {
                            Id = 62,
                            Brand = "Toyota",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7364),
                            IsDeleted = false,
                            Model = "RAV4"
                        },
                        new
                        {
                            Id = 63,
                            Brand = "Toyota",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7366),
                            IsDeleted = false,
                            Model = "Land Cruiser"
                        },
                        new
                        {
                            Id = 64,
                            Brand = "Toyota",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7368),
                            IsDeleted = false,
                            Model = "Hilux"
                        },
                        new
                        {
                            Id = 65,
                            Brand = "Kia",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7370),
                            IsDeleted = false,
                            Model = "Sorento"
                        },
                        new
                        {
                            Id = 66,
                            Brand = "Kia",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7372),
                            IsDeleted = false,
                            Model = "Sportage"
                        },
                        new
                        {
                            Id = 67,
                            Brand = "Kia",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7373),
                            IsDeleted = false,
                            Model = "K5"
                        },
                        new
                        {
                            Id = 68,
                            Brand = "Kia",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7375),
                            IsDeleted = false,
                            Model = "Stinger"
                        },
                        new
                        {
                            Id = 69,
                            Brand = "Hyundai",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7377),
                            IsDeleted = false,
                            Model = "Sonata"
                        },
                        new
                        {
                            Id = 70,
                            Brand = "Hyundai",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7379),
                            IsDeleted = false,
                            Model = "Tucson"
                        },
                        new
                        {
                            Id = 71,
                            Brand = "Hyundai",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7380),
                            IsDeleted = false,
                            Model = "Elantra"
                        },
                        new
                        {
                            Id = 72,
                            Brand = "Hyundai",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7382),
                            IsDeleted = false,
                            Model = "Kona"
                        },
                        new
                        {
                            Id = 73,
                            Brand = "Hyundai",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7384),
                            IsDeleted = false,
                            Model = "Palisade"
                        },
                        new
                        {
                            Id = 74,
                            Brand = "Mitsubishi",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7386),
                            IsDeleted = false,
                            Model = "Outlander"
                        },
                        new
                        {
                            Id = 75,
                            Brand = "Mitsubishi",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7388),
                            IsDeleted = false,
                            Model = "Lancer"
                        },
                        new
                        {
                            Id = 76,
                            Brand = "Mitsubishi",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7390),
                            IsDeleted = false,
                            Model = "Eclipse"
                        },
                        new
                        {
                            Id = 77,
                            Brand = "Lada",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7392),
                            IsDeleted = false,
                            Model = "Granta"
                        },
                        new
                        {
                            Id = 78,
                            Brand = "Lada",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7394),
                            IsDeleted = false,
                            Model = "Vesta"
                        },
                        new
                        {
                            Id = 79,
                            Brand = "Lada",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7395),
                            IsDeleted = false,
                            Model = "XRay"
                        },
                        new
                        {
                            Id = 80,
                            Brand = "Volkswagen",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7397),
                            IsDeleted = false,
                            Model = "Golf"
                        },
                        new
                        {
                            Id = 81,
                            Brand = "Volkswagen",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7399),
                            IsDeleted = false,
                            Model = "Passat"
                        },
                        new
                        {
                            Id = 82,
                            Brand = "Volkswagen",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7401),
                            IsDeleted = false,
                            Model = "Tiguan"
                        },
                        new
                        {
                            Id = 83,
                            Brand = "Volkswagen",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7403),
                            IsDeleted = false,
                            Model = "Jetta"
                        },
                        new
                        {
                            Id = 84,
                            Brand = "Ford",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7404),
                            IsDeleted = false,
                            Model = "Mustang"
                        },
                        new
                        {
                            Id = 85,
                            Brand = "Ford",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7406),
                            IsDeleted = false,
                            Model = "F-150"
                        },
                        new
                        {
                            Id = 86,
                            Brand = "Land Rover",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7408),
                            IsDeleted = false,
                            Model = "Range Rover"
                        },
                        new
                        {
                            Id = 87,
                            Brand = "Land Rover",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7410),
                            IsDeleted = false,
                            Model = "Discovery"
                        },
                        new
                        {
                            Id = 88,
                            Brand = "Porsche",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7411),
                            IsDeleted = false,
                            Model = "911"
                        },
                        new
                        {
                            Id = 89,
                            Brand = "Porsche",
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(7413),
                            IsDeleted = false,
                            Model = "Cayenne"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Colors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9839),
                            IsDeleted = false,
                            Name = "Ağ"
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9845),
                            IsDeleted = false,
                            Name = "Qara"
                        },
                        new
                        {
                            Id = 3,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9846),
                            IsDeleted = false,
                            Name = "Qırmızı"
                        },
                        new
                        {
                            Id = 4,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9848),
                            IsDeleted = false,
                            Name = "Yaşıl"
                        },
                        new
                        {
                            Id = 5,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9849),
                            IsDeleted = false,
                            Name = "Mavi"
                        },
                        new
                        {
                            Id = 6,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9850),
                            IsDeleted = false,
                            Name = "Sarı"
                        },
                        new
                        {
                            Id = 7,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9851),
                            IsDeleted = false,
                            Name = "Narıncı"
                        },
                        new
                        {
                            Id = 8,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9852),
                            IsDeleted = false,
                            Name = "Bənövşəyi"
                        },
                        new
                        {
                            Id = 9,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9855),
                            IsDeleted = false,
                            Name = "Çəhrayı"
                        },
                        new
                        {
                            Id = 10,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9856),
                            IsDeleted = false,
                            Name = "Boz"
                        },
                        new
                        {
                            Id = 11,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9857),
                            IsDeleted = false,
                            Name = "Qəhvəyi"
                        },
                        new
                        {
                            Id = 12,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9858),
                            IsDeleted = false,
                            Name = "Göy"
                        },
                        new
                        {
                            Id = 13,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9859),
                            IsDeleted = false,
                            Name = "Tünd yaşıl"
                        },
                        new
                        {
                            Id = 14,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9860),
                            IsDeleted = false,
                            Name = "Açıq yaşıl"
                        },
                        new
                        {
                            Id = 15,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9861),
                            IsDeleted = false,
                            Name = "Tünd mavi"
                        },
                        new
                        {
                            Id = 16,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9863),
                            IsDeleted = false,
                            Name = "Açıq mavi"
                        },
                        new
                        {
                            Id = 17,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9863),
                            IsDeleted = false,
                            Name = "Tünd qəhvəyi"
                        },
                        new
                        {
                            Id = 18,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9864),
                            IsDeleted = false,
                            Name = "Açıq qəhvəyi"
                        },
                        new
                        {
                            Id = 19,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9865),
                            IsDeleted = false,
                            Name = "Bürünc"
                        },
                        new
                        {
                            Id = 20,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9867),
                            IsDeleted = false,
                            Name = "Gümüşü"
                        },
                        new
                        {
                            Id = 21,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 346, DateTimeKind.Local).AddTicks(9867),
                            IsDeleted = false,
                            Name = "Qızılı"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Commits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommitMessage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CustumerId")
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustumerId");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("Domain.Entities.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 347, DateTimeKind.Local).AddTicks(9039),
                            IsDeleted = false,
                            Name = "Master Admin",
                            Password = "$2a$11$gZdTV78QAwiPRpd8n11MLe8p111KlStD/xo1/1qUXUBifJnwZuj8K",
                            Phone = "+994000",
                            RefreshToken = "qOLhGm3T0r6938al5PjO2nyYbnLajCGQP/XU6CJkcZ4=",
                            RefreshTokenExpiryTime = new DateTime(2025, 2, 9, 22, 17, 22, 347, DateTimeKind.Local).AddTicks(9017),
                            RoleId = 2,
                            Surname = "Master"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CustomersCarsMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ColorsId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Motor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FuelTypeId");

                    b.ToTable("CustomersCarsMatrix");
                });

            modelBuilder.Entity("Domain.Entities.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(1420),
                            IsDeleted = false,
                            Name = "Master Employee",
                            Surname = "Master"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Filters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Filters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(3708),
                            IsDeleted = false,
                            Name = "Yağ"
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(3710),
                            IsDeleted = false,
                            Name = "Hava"
                        },
                        new
                        {
                            Id = 3,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(3712),
                            IsDeleted = false,
                            Name = "Yanacaq"
                        },
                        new
                        {
                            Id = 4,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(3714),
                            IsDeleted = false,
                            Name = "Salon"
                        });
                });

            modelBuilder.Entity("Domain.Entities.FuelTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(6080),
                            IsDeleted = false,
                            Name = "Benzin"
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(6083),
                            IsDeleted = false,
                            Name = "Qaz"
                        },
                        new
                        {
                            Id = 3,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(6085),
                            IsDeleted = false,
                            Name = "Dizel"
                        },
                        new
                        {
                            Id = 4,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(6086),
                            IsDeleted = false,
                            Name = "Elektro"
                        },
                        new
                        {
                            Id = 5,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(6088),
                            IsDeleted = false,
                            Name = "Hybrid"
                        },
                        new
                        {
                            Id = 6,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(6090),
                            IsDeleted = false,
                            Name = "Plug-in Hybrid"
                        },
                        new
                        {
                            Id = 7,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 348, DateTimeKind.Local).AddTicks(6092),
                            IsDeleted = false,
                            Name = "Hidrogen"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OilChangeFiltersMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FiltersId")
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OilChangesId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FiltersId");

                    b.HasIndex("OilChangesId");

                    b.ToTable("OilChangeFiltersMatrix");
                });

            modelBuilder.Entity("Domain.Entities.OilChanges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomersCarsMatrixId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KilometersTravelled")
                        .HasColumnType("int");

                    b.Property<int>("OilTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomersCarsMatrixId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OilTypeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.OilTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OilTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 353, DateTimeKind.Local).AddTicks(3120),
                            IsDeleted = false,
                            Name = "5-30"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Phones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 353, DateTimeKind.Local).AddTicks(8897),
                            IsDeleted = false,
                            Phone = "+994703305788"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 2,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 353, DateTimeKind.Local).AddTicks(8901),
                            IsDeleted = false,
                            Phone = "+994702343134"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 3,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 353, DateTimeKind.Local).AddTicks(8903),
                            IsDeleted = false,
                            Phone = "+994707552322"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 4,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 353, DateTimeKind.Local).AddTicks(8906),
                            IsDeleted = false,
                            Phone = "+994077332322"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 354, DateTimeKind.Local).AddTicks(779),
                            IsDeleted = false,
                            Name = "Elf"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 354, DateTimeKind.Local).AddTicks(2508),
                            IsDeleted = false,
                            RoleName = "Costumer"
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 354, DateTimeKind.Local).AddTicks(2511),
                            IsDeleted = false,
                            RoleName = "Branch"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 354, DateTimeKind.Local).AddTicks(4825),
                            IsDeleted = false,
                            Name = "Sürətlər qutusu yağ dəyişmə"
                        },
                        new
                        {
                            Id = 2,
                            InsertedBy = 1,
                            InsertedDate = new DateTime(2024, 12, 9, 22, 17, 22, 354, DateTimeKind.Local).AddTicks(4828),
                            IsDeleted = false,
                            Name = "Mühərrik yağ dəyişmə"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Commits", b =>
                {
                    b.HasOne("Domain.Entities.Customers", "Customers")
                        .WithMany("Commits")
                        .HasForeignKey("CustumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Domain.Entities.Customers", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.CustomersCarsMatrix", b =>
                {
                    b.HasOne("Domain.Entities.Cars", "Cars")
                        .WithMany("UsersCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Colors", "Colors")
                        .WithMany("UsersCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Customers", "Customers")
                        .WithMany("CustomersCars")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FuelTypes", "FuelType")
                        .WithMany("UsersCars")
                        .HasForeignKey("FuelTypeId");

                    b.Navigation("Cars");

                    b.Navigation("Colors");

                    b.Navigation("Customers");

                    b.Navigation("FuelType");
                });

            modelBuilder.Entity("Domain.Entities.OilChangeFiltersMatrix", b =>
                {
                    b.HasOne("Domain.Entities.Filters", "Filter")
                        .WithMany("OilChangeFilters")
                        .HasForeignKey("FiltersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OilChanges", "OilChanges")
                        .WithMany("OilChangeFilters")
                        .HasForeignKey("OilChangesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filter");

                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.OilChanges", b =>
                {
                    b.HasOne("Domain.Entities.Branchies", "Branchies")
                        .WithMany("OilChanges")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CustomersCarsMatrix", "CustomersCarsMatrix")
                        .WithMany("OilChanges")
                        .HasForeignKey("CustomersCarsMatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employees", "Employees")
                        .WithMany("OilChanges")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OilTypes", "OilTypes")
                        .WithMany("OilChanges")
                        .HasForeignKey("OilTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Products", "Products")
                        .WithMany("OilChanges")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Services", "Services")
                        .WithMany("OilChanges")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branchies");

                    b.Navigation("CustomersCarsMatrix");

                    b.Navigation("Employees");

                    b.Navigation("OilTypes");

                    b.Navigation("Products");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Entities.Phones", b =>
                {
                    b.HasOne("Domain.Entities.Branchies", "Branchies")
                        .WithMany("Phones")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branchies");
                });

            modelBuilder.Entity("Domain.Entities.Branchies", b =>
                {
                    b.Navigation("OilChanges");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Domain.Entities.Cars", b =>
                {
                    b.Navigation("UsersCars");
                });

            modelBuilder.Entity("Domain.Entities.Colors", b =>
                {
                    b.Navigation("UsersCars");
                });

            modelBuilder.Entity("Domain.Entities.Customers", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("CustomersCars");
                });

            modelBuilder.Entity("Domain.Entities.CustomersCarsMatrix", b =>
                {
                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.Employees", b =>
                {
                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.Filters", b =>
                {
                    b.Navigation("OilChangeFilters");
                });

            modelBuilder.Entity("Domain.Entities.FuelTypes", b =>
                {
                    b.Navigation("UsersCars");
                });

            modelBuilder.Entity("Domain.Entities.OilChanges", b =>
                {
                    b.Navigation("OilChangeFilters");
                });

            modelBuilder.Entity("Domain.Entities.OilTypes", b =>
                {
                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.Products", b =>
                {
                    b.Navigation("OilChanges");
                });

            modelBuilder.Entity("Domain.Entities.Services", b =>
                {
                    b.Navigation("OilChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
